<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CrossfitUser;
use AppBundle\Entity\Exercise;
use AppBundle\Entity\ExerciseCategory;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends \Doctrine\ORM\EntityRepository
{

    public function createExercise($name, ExerciseCategory $exerciseCategory, CrossfitUser $crossfitUser)
    {
        $exercise = new Exercise();
        $exercise
            ->setName($name)
            ->setExerciseCategory($exerciseCategory)
            ->setCreatedBy($crossfitUser);

        $this->getEntityManager()->persist($exercise);
        $this->getEntityManager()->flush();
    }
}
