<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CrossfitUser;
use AppBundle\Entity\ExerciseCategory;

/**
 * ExerciseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseCategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function createExerciseCategory($name, CrossfitUser $crossfitUser)
    {
        $exerciseCategory = new ExerciseCategory();
        $exerciseCategory->setName($name)
            ->setCreatedBy($crossfitUser);

        $this->getEntityManager()->persist($exerciseCategory);
        $this->getEntityManager()->flush();
    }
}
